name: bill_scanner_app
description: Bill Scanner + Expense Tracker using OCR and Gemini AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  file_picker: ^8.0.0
  image_picker: ^1.0.7

  google_mlkit_text_recognition: ^0.11.0
  google_generative_ai: ^0.4.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_riverpod: ^2.5.1

  fl_chart: ^0.68.0
  intl: ^0.19.0

  path_provider: ^2.1.2

  flutter_local_notifications: ^17.2.4
  permission_handler: ^11.4.0

  flutter_dotenv: ^5.2.1

  uuid: ^4.3.3

  cupertino_icons: ^1.0.6

  # 🔥 Correct PDF reader
  syncfusion_flutter_pdf: ^28.1.33
  syncfusion_flutter_pdfviewer: ^28.1.33

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - .env