// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZFRanU_z_znUM4o2pUt35XLesD6dMX8A',
    appId: '1:267094691381:web:f32a6f20f4a97cc4b9eb7c',
    messagingSenderId: '267094691381',
    projectId: 'bill-scanner-app-8dec4',
    authDomain: 'bill-scanner-app-8dec4.firebaseapp.com',
    storageBucket: 'bill-scanner-app-8dec4.firebasestorage.app',
    measurementId: 'G-3X19X3RKXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZtmzl0X0OZNGaH0pm8JK9qo6ICeV9yc',
    appId: '1:267094691381:android:468b8b46c56369f9b9eb7c',
    messagingSenderId: '267094691381',
    projectId: 'bill-scanner-app-8dec4',
    storageBucket: 'bill-scanner-app-8dec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY_0qmBa8pL1S4tapTWTK_avmGgRkx5hs',
    appId: '1:267094691381:ios:bc27eff028d772a2b9eb7c',
    messagingSenderId: '267094691381',
    projectId: 'bill-scanner-app-8dec4',
    storageBucket: 'bill-scanner-app-8dec4.firebasestorage.app',
    iosBundleId: 'com.example.billScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY_0qmBa8pL1S4tapTWTK_avmGgRkx5hs',
    appId: '1:267094691381:ios:bc27eff028d772a2b9eb7c',
    messagingSenderId: '267094691381',
    projectId: 'bill-scanner-app-8dec4',
    storageBucket: 'bill-scanner-app-8dec4.firebasestorage.app',
    iosBundleId: 'com.example.billScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZFRanU_z_znUM4o2pUt35XLesD6dMX8A',
    appId: '1:267094691381:web:ec21b824cd1fc1bcb9eb7c',
    messagingSenderId: '267094691381',
    projectId: 'bill-scanner-app-8dec4',
    authDomain: 'bill-scanner-app-8dec4.firebaseapp.com',
    storageBucket: 'bill-scanner-app-8dec4.firebasestorage.app',
    measurementId: 'G-3H3WY94XLL',
  );
}
